name: LyttleNametag
description: Custom nametags plugin
version: '${projectVersion}'
main: com.lyttledev.lyttlenametag.LyttleNametag
api-version: '1.21'
authors:
  - LyttleDevelopment
  - ThatsATim
  - Stualyttle


softdepend:
  - PlaceholderAPI
  # Needed for Packet Events compatibility:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

commands:
  lyttlenametag:
    description: Admin command, mainly reload the config without the rest of the server
    permission: lyttlenametag.lyttlenametag