name: Release and Publish Artifacts

on:
  push:
    branches:
      - alpha

jobs:
  build-and-release:
    if: github.repository_owner == 'Lyttle-Development'
    runs-on: ubuntu-22.04
    env:
      GPR_USER: ${{ secrets.GPR_USER }}
      GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          check-latest: true

      - name: Build project
        run: ./gradlew build --stacktrace

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: build/libs/*.jar

      - name: Get version from Gradle
        id: get_version
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create git tag for release
        id: tag_release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a v${{ steps.get_version.outputs.version }} -m "Alpha v${{ steps.get_version.outputs.version }}"
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Create GitHub Alpha and Upload JAR
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-hangar:
    needs: build-and-release
    if: github.repository_owner == 'Lyttle-Development'
    runs-on: ubuntu-22.04
    env:
      HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
      CHANNEL: Alpha
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-jar
          path: ./dist

      - name: Publish to Hangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          CHANNEL: Alpha
        run: |
          ./gradlew publishPluginJarToHangar -PjarPath=./dist/*.jar --stacktrace

  publish-modrinth:
    needs: build-and-release
    if: github.repository_owner == 'Lyttle-Development'
    runs-on: ubuntu-22.04
    env:
      MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}
      CHANNEL: Alpha
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-jar
          path: ./dist

      - name: Publish to Modrinth
        env:
          MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}
          CHANNEL: Alpha
        run: |
          ./gradlew publishPluginJarToModrinth -PjarPath=./dist/*.jar --stacktrace
